import type { Ghat } from "./types";

// Real Godavari ghats with approximate coordinates
export const INITIAL_GHATS: Ghat[] = [
  { id: "g1",  name: "Pushkar Ghat",        district: "East Godavari", riverSide: "South", cameraId: "CAM-001", latitude: 16.9891, longitude: 81.7842, maximumCapacity: 5000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g2",  name: "Kotilingala Ghat",    district: "East Godavari", riverSide: "South", cameraId: "CAM-002", latitude: 16.9905, longitude: 81.7799, maximumCapacity: 4500, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g3",  name: "ISKCON Ghat",         district: "East Godavari", riverSide: "South", cameraId: "CAM-003", latitude: 16.9856, longitude: 81.7891, maximumCapacity: 3000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g4",  name: "Saraswati Ghat",      district: "East Godavari", riverSide: "South", cameraId: "CAM-004", latitude: 16.9820, longitude: 81.7920, maximumCapacity: 3500, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g5",  name: "Markandeya Ghat",     district: "East Godavari", riverSide: "South", cameraId: "CAM-005", latitude: 16.9938, longitude: 81.7750, maximumCapacity: 2500, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g6",  name: "Dowleswaram Ghat",    district: "East Godavari", riverSide: "South", cameraId: "CAM-006", latitude: 16.9430, longitude: 81.7780, maximumCapacity: 4000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g7",  name: "Kovvur Ghat",         district: "West Godavari", riverSide: "North", cameraId: "CAM-007", latitude: 17.0156, longitude: 81.7350, maximumCapacity: 3800, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g8",  name: "Yanam Ghat",          district: "Yanam",         riverSide: "East",  cameraId: "CAM-008", latitude: 16.7305, longitude: 82.2170, maximumCapacity: 2800, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g9",  name: "Nidadavole Ghat",     district: "West Godavari", riverSide: "North", cameraId: "CAM-009", latitude: 16.9100, longitude: 81.6700, maximumCapacity: 2200, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "offline", lastUpdated: new Date().toISOString() },
  { id: "g10", name: "Bhadrachalam Ghat",   district: "Bhadradri",     riverSide: "North", cameraId: "CAM-010", latitude: 17.6688, longitude: 80.8881, maximumCapacity: 6000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g11", name: "Rajamahendravaram Old Ghat", district: "East Godavari", riverSide: "South", cameraId: "CAM-011", latitude: 16.9870, longitude: 81.7810, maximumCapacity: 4200, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g12", name: "Polavaram Ghat",      district: "West Godavari", riverSide: "North", cameraId: "CAM-012", latitude: 17.2510, longitude: 81.6420, maximumCapacity: 3300, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g13", name: "Gowthami Ghat",       district: "East Godavari", riverSide: "South", cameraId: "CAM-013", latitude: 16.9800, longitude: 81.7950, maximumCapacity: 3500, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g14", name: "TTD Ghat",            district: "East Godavari", riverSide: "South", cameraId: "CAM-014", latitude: 16.9840, longitude: 81.7900, maximumCapacity: 2800, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g15", name: "Chintalamma Ghat",    district: "East Godavari", riverSide: "South", cameraId: "CAM-015", latitude: 16.8500, longitude: 81.8500, maximumCapacity: 1500, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g16", name: "Kotipalli Ghat",      district: "East Godavari", riverSide: "South", cameraId: "CAM-016", latitude: 16.6576, longitude: 82.0460, maximumCapacity: 4000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g17", name: "Mukteswaram Ghat",    district: "East Godavari", riverSide: "South", cameraId: "CAM-017", latitude: 16.6710, longitude: 81.9700, maximumCapacity: 2000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g18", name: "Yanam Ferry Ghat",    district: "Yanam",         riverSide: "East",  cameraId: "CAM-018", latitude: 16.7300, longitude: 82.2150, maximumCapacity: 2500, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g19", name: "Pattiseema Ghat",     district: "West Godavari", riverSide: "North", cameraId: "CAM-019", latitude: 17.2285, longitude: 81.6033, maximumCapacity: 3000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g20", name: "Dowleswaram Barrage Ghat", district: "East Godavari", riverSide: "South", cameraId: "CAM-020", latitude: 16.9420, longitude: 81.7770, maximumCapacity: 4000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g21", name: "Antarvedi Ghat",      district: "East Godavari", riverSide: "South", cameraId: "CAM-021", latitude: 16.3262, longitude: 81.7335, maximumCapacity: 5000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g22", name: "Narsapur Ghat",       district: "West Godavari", riverSide: "North", cameraId: "CAM-022", latitude: 16.4382, longitude: 81.6961, maximumCapacity: 4500, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g23", name: "Kaleshwaram Ghat",    district: "Jayashankar",   riverSide: "South", cameraId: "CAM-023", latitude: 18.8155, longitude: 79.9073, maximumCapacity: 6000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g24", name: "Basara Ghat",         district: "Nirmal",        riverSide: "South", cameraId: "CAM-024", latitude: 18.8809, longitude: 77.9542, maximumCapacity: 5500, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g25", name: "Dharmapuri Ghat",     district: "Jagtial",       riverSide: "South", cameraId: "CAM-025", latitude: 18.9500, longitude: 79.0881, maximumCapacity: 4000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g26", name: "Ramagundam Ghat",     district: "Peddapalli",    riverSide: "South", cameraId: "CAM-026", latitude: 18.7563, longitude: 79.4880, maximumCapacity: 3500, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g27", name: "Manthani Ghat",       district: "Peddapalli",    riverSide: "South", cameraId: "CAM-027", latitude: 18.6473, longitude: 79.6644, maximumCapacity: 2500, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g28", name: "Eturunagaram Ghat",   district: "Mulugu",        riverSide: "South", cameraId: "CAM-028", latitude: 18.3375, longitude: 80.4287, maximumCapacity: 3000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g29", name: "Kaleshwaram Sangam Ghat", district: "Jayashankar", riverSide: "South", cameraId: "CAM-029", latitude: 18.8170, longitude: 79.9100, maximumCapacity: 4500, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g30", name: "Sriram Sagar Ghat",   district: "Nizamabad",     riverSide: "South", cameraId: "CAM-030", latitude: 18.9669, longitude: 78.3316, maximumCapacity: 3800, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g31", name: "Nagarjuna Sagar Ghat",district: "Nalgonda",      riverSide: "South", cameraId: "CAM-031", latitude: 16.5772, longitude: 79.3134, maximumCapacity: 4000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g32", name: "Vijayawada Durga Ghat", district: "NTR",         riverSide: "North", cameraId: "CAM-032", latitude: 16.5147, longitude: 80.6094, maximumCapacity: 6000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g33", name: "Krishna Pushkar Ghat",district: "NTR",           riverSide: "North", cameraId: "CAM-033", latitude: 16.5100, longitude: 80.6000, maximumCapacity: 5000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g34", name: "Bhavani Ghat",        district: "NTR",           riverSide: "North", cameraId: "CAM-034", latitude: 16.5218, longitude: 80.5901, maximumCapacity: 4500, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g35", name: "Punnami Ghat",        district: "NTR",           riverSide: "North", cameraId: "CAM-035", latitude: 16.5173, longitude: 80.6050, maximumCapacity: 4000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g36", name: "Ibrahimpatnam Ghat",  district: "NTR",           riverSide: "North", cameraId: "CAM-036", latitude: 16.5925, longitude: 80.5284, maximumCapacity: 3500, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g37", name: "Amaravati Ghat",      district: "Palnadu",       riverSide: "South", cameraId: "CAM-037", latitude: 16.5786, longitude: 80.3582, maximumCapacity: 4200, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g38", name: "Sitanagaram Ghat",    district: "Guntur",        riverSide: "South", cameraId: "CAM-038", latitude: 16.5029, longitude: 80.6040, maximumCapacity: 3800, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g39", name: "Hamsaladeevi Ghat",   district: "Krishna",       riverSide: "North", cameraId: "CAM-039", latitude: 15.8211, longitude: 80.9754, maximumCapacity: 3000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g40", name: "Srisailam Ghat",      district: "Nandyal",       riverSide: "South", cameraId: "CAM-040", latitude: 16.0848, longitude: 78.8752, maximumCapacity: 5000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g41", name: "Sangameswaram Ghat",  district: "Nandyal",       riverSide: "South", cameraId: "CAM-041", latitude: 16.0125, longitude: 78.3245, maximumCapacity: 2500, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g42", name: "Mahanandi Temple Tank", district: "Nandyal",     riverSide: "South", cameraId: "CAM-042", latitude: 15.4850, longitude: 78.6234, maximumCapacity: 1500, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g43", name: "Penna River Ghat",    district: "Nellore",       riverSide: "South", cameraId: "CAM-043", latitude: 14.4534, longitude: 79.9867, maximumCapacity: 3000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g44", name: "Gandikota Ghat",      district: "Kadapa",        riverSide: "South", cameraId: "CAM-044", latitude: 14.8143, longitude: 78.2863, maximumCapacity: 2000, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g45", name: "Somasila Ghat",       district: "Nellore",       riverSide: "South", cameraId: "CAM-045", latitude: 14.4842, longitude: 79.3101, maximumCapacity: 2800, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g46", name: "Nagavali Ghat",       district: "Srikakulam",    riverSide: "South", cameraId: "CAM-046", latitude: 18.3039, longitude: 83.8967, maximumCapacity: 3500, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
  { id: "g47", name: "Vamsadhara Ghat",     district: "Srikakulam",    riverSide: "South", cameraId: "CAM-047", latitude: 18.3340, longitude: 84.1190, maximumCapacity: 3200, currentPeople: 0, occupancyPercentage: 0, status: "safe", cameraHealth: "online",  lastUpdated: new Date().toISOString() },
];

export function computeStatus(occ: number): "safe" | "moderate" | "critical" {
  if (occ > 80) return "critical";
  if (occ > 40) return "moderate";
  return "safe";
}
