/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectGhatRouteImport } from './routes/select-ghat'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AddStreamsRouteImport } from './routes/add-streams'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'

const SelectGhatRoute = SelectGhatRouteImport.update({
  id: '/select-ghat',
  path: '/select-ghat',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AddStreamsRoute = AddStreamsRouteImport.update({
  id: '/add-streams',
  path: '/add-streams',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/add-streams': typeof AddStreamsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRoute
  '/select-ghat': typeof SelectGhatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/add-streams': typeof AddStreamsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRoute
  '/select-ghat': typeof SelectGhatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/add-streams': typeof AddStreamsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRoute
  '/select-ghat': typeof SelectGhatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/add-streams'
    | '/dashboard'
    | '/login'
    | '/operator'
    | '/select-ghat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/add-streams'
    | '/dashboard'
    | '/login'
    | '/operator'
    | '/select-ghat'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/add-streams'
    | '/dashboard'
    | '/login'
    | '/operator'
    | '/select-ghat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AddStreamsRoute: typeof AddStreamsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OperatorRoute: typeof OperatorRoute
  SelectGhatRoute: typeof SelectGhatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-ghat': {
      id: '/select-ghat'
      path: '/select-ghat'
      fullPath: '/select-ghat'
      preLoaderRoute: typeof SelectGhatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-streams': {
      id: '/add-streams'
      path: '/add-streams'
      fullPath: '/add-streams'
      preLoaderRoute: typeof AddStreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AddStreamsRoute: AddStreamsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OperatorRoute: OperatorRoute,
  SelectGhatRoute: SelectGhatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
